# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'campRegAddNewApplicant.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_DialogAddNewApplicant(object):
    def setupUi(self, DialogAddNewApplicant):
        DialogAddNewApplicant.setObjectName(_fromUtf8("DialogAddNewApplicant"))
        DialogAddNewApplicant.resize(1297, 1010)
        DialogAddNewApplicant.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        DialogAddNewApplicant.setAutoFillBackground(False)
        DialogAddNewApplicant.setSizeGripEnabled(False)
        self.gridLayout = QtGui.QGridLayout(DialogAddNewApplicant)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.labelGender = QtGui.QLabel(DialogAddNewApplicant)
        self.labelGender.setObjectName(_fromUtf8("labelGender"))
        self.gridLayout.addWidget(self.labelGender, 1, 3, 1, 1)
        self.lineGender = QtGui.QLineEdit(DialogAddNewApplicant)
        self.lineGender.setObjectName(_fromUtf8("lineGender"))
        self.gridLayout.addWidget(self.lineGender, 1, 4, 1, 1)
        self.dateApplicationDate = QtGui.QDateEdit(DialogAddNewApplicant)
        self.dateApplicationDate.setObjectName(_fromUtf8("dateApplicationDate"))
        self.gridLayout.addWidget(self.dateApplicationDate, 16, 2, 1, 1)
        self.labelLastName = QtGui.QLabel(DialogAddNewApplicant)
        self.labelLastName.setObjectName(_fromUtf8("labelLastName"))
        self.gridLayout.addWidget(self.labelLastName, 2, 1, 1, 1)
        self.label_18 = QtGui.QLabel(DialogAddNewApplicant)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout.addWidget(self.label_18, 0, 1, 1, 2)
        self.labelFirstName = QtGui.QLabel(DialogAddNewApplicant)
        self.labelFirstName.setObjectName(_fromUtf8("labelFirstName"))
        self.gridLayout.addWidget(self.labelFirstName, 1, 1, 1, 1)
        self.labelApplicationDate = QtGui.QLabel(DialogAddNewApplicant)
        self.labelApplicationDate.setObjectName(_fromUtf8("labelApplicationDate"))
        self.gridLayout.addWidget(self.labelApplicationDate, 16, 1, 1, 1)
        self.lineLastName = QtGui.QLineEdit(DialogAddNewApplicant)
        self.lineLastName.setObjectName(_fromUtf8("lineLastName"))
        self.gridLayout.addWidget(self.lineLastName, 2, 2, 1, 1)
        self.labelDOB = QtGui.QLabel(DialogAddNewApplicant)
        self.labelDOB.setObjectName(_fromUtf8("labelDOB"))
        self.gridLayout.addWidget(self.labelDOB, 2, 3, 1, 1)
        self.lineFirstName = QtGui.QLineEdit(DialogAddNewApplicant)
        self.lineFirstName.setObjectName(_fromUtf8("lineFirstName"))
        self.gridLayout.addWidget(self.lineFirstName, 1, 2, 1, 1)
        self.dateReviewDate = QtGui.QDateEdit(DialogAddNewApplicant)
        self.dateReviewDate.setObjectName(_fromUtf8("dateReviewDate"))
        self.gridLayout.addWidget(self.dateReviewDate, 16, 4, 1, 1)
        self.comboBoxBunkhouse = QtGui.QComboBox(DialogAddNewApplicant)
        self.comboBoxBunkhouse.setObjectName(_fromUtf8("comboBoxBunkhouse"))
        self.gridLayout.addWidget(self.comboBoxBunkhouse, 20, 2, 1, 1)
        self.labelReviewDate = QtGui.QLabel(DialogAddNewApplicant)
        self.labelReviewDate.setObjectName(_fromUtf8("labelReviewDate"))
        self.gridLayout.addWidget(self.labelReviewDate, 16, 3, 1, 1)
        self.labelAcceptanceDecision = QtGui.QLabel(DialogAddNewApplicant)
        self.labelAcceptanceDecision.setObjectName(_fromUtf8("labelAcceptanceDecision"))
        self.gridLayout.addWidget(self.labelAcceptanceDecision, 17, 3, 1, 1)
        self.comboBoxTribe = QtGui.QComboBox(DialogAddNewApplicant)
        self.comboBoxTribe.setObjectName(_fromUtf8("comboBoxTribe"))
        self.gridLayout.addWidget(self.comboBoxTribe, 20, 4, 1, 1)
        self.labelPayment = QtGui.QLabel(DialogAddNewApplicant)
        self.labelPayment.setObjectName(_fromUtf8("labelPayment"))
        self.gridLayout.addWidget(self.labelPayment, 17, 1, 1, 1)
        self.line = QtGui.QFrame(DialogAddNewApplicant)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout.addWidget(self.line, 6, 1, 1, 4)
        self.labelBunkhouse = QtGui.QLabel(DialogAddNewApplicant)
        self.labelBunkhouse.setObjectName(_fromUtf8("labelBunkhouse"))
        self.gridLayout.addWidget(self.labelBunkhouse, 20, 1, 1, 1)
        self.checkBoxPayment = QtGui.QCheckBox(DialogAddNewApplicant)
        self.checkBoxPayment.setObjectName(_fromUtf8("checkBoxPayment"))
        self.gridLayout.addWidget(self.checkBoxPayment, 17, 2, 1, 1)
        self.label_5 = QtGui.QLabel(DialogAddNewApplicant)
        self.label_5.setMinimumSize(QtCore.QSize(90, 0))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 7, 1, 1, 1)
        self.lineEmergencyPhone = QtGui.QLineEdit(DialogAddNewApplicant)
        self.lineEmergencyPhone.setObjectName(_fromUtf8("lineEmergencyPhone"))
        self.gridLayout.addWidget(self.lineEmergencyPhone, 13, 4, 1, 1)
        self.labelEquipmentsCheck = QtGui.QLabel(DialogAddNewApplicant)
        self.labelEquipmentsCheck.setObjectName(_fromUtf8("labelEquipmentsCheck"))
        self.gridLayout.addWidget(self.labelEquipmentsCheck, 18, 3, 1, 1)
        self.lineLine1 = QtGui.QLineEdit(DialogAddNewApplicant)
        self.lineLine1.setObjectName(_fromUtf8("lineLine1"))
        self.gridLayout.addWidget(self.lineLine1, 8, 2, 1, 1)
        self.lineCellPhone = QtGui.QLineEdit(DialogAddNewApplicant)
        self.lineCellPhone.setObjectName(_fromUtf8("lineCellPhone"))
        self.gridLayout.addWidget(self.lineCellPhone, 5, 2, 1, 1)
        self.labelLine2 = QtGui.QLabel(DialogAddNewApplicant)
        self.labelLine2.setObjectName(_fromUtf8("labelLine2"))
        self.gridLayout.addWidget(self.labelLine2, 8, 3, 1, 1)
        self.lineEmail = QtGui.QLineEdit(DialogAddNewApplicant)
        self.lineEmail.setObjectName(_fromUtf8("lineEmail"))
        self.gridLayout.addWidget(self.lineEmail, 4, 2, 1, 1)
        self.comboBoxCamp = QtGui.QComboBox(DialogAddNewApplicant)
        self.comboBoxCamp.setObjectName(_fromUtf8("comboBoxCamp"))
        self.gridLayout.addWidget(self.comboBoxCamp, 5, 4, 1, 1)
        self.lineHomePhone = QtGui.QLineEdit(DialogAddNewApplicant)
        self.lineHomePhone.setObjectName(_fromUtf8("lineHomePhone"))
        self.gridLayout.addWidget(self.lineHomePhone, 4, 4, 1, 1)
        self.comboBoxAcceptanceDecision = QtGui.QComboBox(DialogAddNewApplicant)
        self.comboBoxAcceptanceDecision.setObjectName(_fromUtf8("comboBoxAcceptanceDecision"))
        self.gridLayout.addWidget(self.comboBoxAcceptanceDecision, 17, 4, 1, 1)
        self.checkBoxFormsCheck = QtGui.QCheckBox(DialogAddNewApplicant)
        self.checkBoxFormsCheck.setObjectName(_fromUtf8("checkBoxFormsCheck"))
        self.gridLayout.addWidget(self.checkBoxFormsCheck, 18, 2, 1, 1)
        self.labelLine1 = QtGui.QLabel(DialogAddNewApplicant)
        self.labelLine1.setObjectName(_fromUtf8("labelLine1"))
        self.gridLayout.addWidget(self.labelLine1, 8, 1, 1, 1)
        self.labelCamp = QtGui.QLabel(DialogAddNewApplicant)
        self.labelCamp.setObjectName(_fromUtf8("labelCamp"))
        self.gridLayout.addWidget(self.labelCamp, 5, 3, 1, 1)
        self.labelState = QtGui.QLabel(DialogAddNewApplicant)
        self.labelState.setObjectName(_fromUtf8("labelState"))
        self.gridLayout.addWidget(self.labelState, 9, 3, 1, 1)
        self.labelCity = QtGui.QLabel(DialogAddNewApplicant)
        self.labelCity.setObjectName(_fromUtf8("labelCity"))
        self.gridLayout.addWidget(self.labelCity, 9, 1, 1, 1)
        self.lineCity = QtGui.QLineEdit(DialogAddNewApplicant)
        self.lineCity.setObjectName(_fromUtf8("lineCity"))
        self.gridLayout.addWidget(self.lineCity, 9, 2, 1, 1)
        self.lineZipCode = QtGui.QLineEdit(DialogAddNewApplicant)
        self.lineZipCode.setObjectName(_fromUtf8("lineZipCode"))
        self.gridLayout.addWidget(self.lineZipCode, 10, 2, 1, 1)
        self.labelEmergencyName = QtGui.QLabel(DialogAddNewApplicant)
        self.labelEmergencyName.setObjectName(_fromUtf8("labelEmergencyName"))
        self.gridLayout.addWidget(self.labelEmergencyName, 13, 1, 1, 1)
        self.labelTribe = QtGui.QLabel(DialogAddNewApplicant)
        self.labelTribe.setObjectName(_fromUtf8("labelTribe"))
        self.gridLayout.addWidget(self.labelTribe, 20, 3, 1, 1)
        self.labelFormsCheck = QtGui.QLabel(DialogAddNewApplicant)
        self.labelFormsCheck.setObjectName(_fromUtf8("labelFormsCheck"))
        self.gridLayout.addWidget(self.labelFormsCheck, 18, 1, 1, 1)
        self.lineState = QtGui.QLineEdit(DialogAddNewApplicant)
        self.lineState.setObjectName(_fromUtf8("lineState"))
        self.gridLayout.addWidget(self.lineState, 9, 4, 1, 1)
        self.label_14 = QtGui.QLabel(DialogAddNewApplicant)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout.addWidget(self.label_14, 12, 1, 1, 1)
        self.lineLine2 = QtGui.QLineEdit(DialogAddNewApplicant)
        self.lineLine2.setObjectName(_fromUtf8("lineLine2"))
        self.gridLayout.addWidget(self.lineLine2, 8, 4, 1, 1)
        self.line_2 = QtGui.QFrame(DialogAddNewApplicant)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.gridLayout.addWidget(self.line_2, 11, 1, 1, 4)
        self.labelCellPhone = QtGui.QLabel(DialogAddNewApplicant)
        self.labelCellPhone.setObjectName(_fromUtf8("labelCellPhone"))
        self.gridLayout.addWidget(self.labelCellPhone, 5, 1, 1, 1)
        self.label_17 = QtGui.QLabel(DialogAddNewApplicant)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout.addWidget(self.label_17, 15, 1, 1, 1)
        self.labelZipCode = QtGui.QLabel(DialogAddNewApplicant)
        self.labelZipCode.setObjectName(_fromUtf8("labelZipCode"))
        self.gridLayout.addWidget(self.labelZipCode, 10, 1, 1, 1)
        self.labelEmail = QtGui.QLabel(DialogAddNewApplicant)
        self.labelEmail.setObjectName(_fromUtf8("labelEmail"))
        self.gridLayout.addWidget(self.labelEmail, 4, 1, 1, 1)
        self.labelHomePhone = QtGui.QLabel(DialogAddNewApplicant)
        self.labelHomePhone.setObjectName(_fromUtf8("labelHomePhone"))
        self.gridLayout.addWidget(self.labelHomePhone, 4, 3, 1, 1)
        self.line_3 = QtGui.QFrame(DialogAddNewApplicant)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.gridLayout.addWidget(self.line_3, 14, 1, 1, 4)
        self.checkBoxEquipmentsCheck = QtGui.QCheckBox(DialogAddNewApplicant)
        self.checkBoxEquipmentsCheck.setObjectName(_fromUtf8("checkBoxEquipmentsCheck"))
        self.gridLayout.addWidget(self.checkBoxEquipmentsCheck, 18, 4, 1, 1)
        self.labelEmergencyPhone = QtGui.QLabel(DialogAddNewApplicant)
        self.labelEmergencyPhone.setObjectName(_fromUtf8("labelEmergencyPhone"))
        self.gridLayout.addWidget(self.labelEmergencyPhone, 13, 3, 1, 1)
        self.lineEmergencyName = QtGui.QLineEdit(DialogAddNewApplicant)
        self.lineEmergencyName.setObjectName(_fromUtf8("lineEmergencyName"))
        self.gridLayout.addWidget(self.lineEmergencyName, 13, 2, 1, 1)
        self.pushButtonSubmit = QtGui.QPushButton(DialogAddNewApplicant)
        self.pushButtonSubmit.setObjectName(_fromUtf8("pushButtonSubmit"))
        self.gridLayout.addWidget(self.pushButtonSubmit, 23, 3, 1, 1)
        self.dateEditDOB = QtGui.QDateEdit(DialogAddNewApplicant)
        self.dateEditDOB.setObjectName(_fromUtf8("dateEditDOB"))
        self.gridLayout.addWidget(self.dateEditDOB, 2, 4, 1, 1)

        self.retranslateUi(DialogAddNewApplicant)
        QtCore.QMetaObject.connectSlotsByName(DialogAddNewApplicant)

    def retranslateUi(self, DialogAddNewApplicant):
        DialogAddNewApplicant.setWindowTitle(_translate("DialogAddNewApplicant", "Add New Applicant", None))
        self.labelGender.setText(_translate("DialogAddNewApplicant", "Gender", None))
        self.labelLastName.setText(_translate("DialogAddNewApplicant", "Last Name", None))
        self.label_18.setText(_translate("DialogAddNewApplicant", "Applicant Basic Information:", None))
        self.labelFirstName.setText(_translate("DialogAddNewApplicant", "First Name", None))
        self.labelApplicationDate.setText(_translate("DialogAddNewApplicant", "Application Date", None))
        self.labelDOB.setText(_translate("DialogAddNewApplicant", "Date of Birth", None))
        self.labelReviewDate.setText(_translate("DialogAddNewApplicant", "Review Date", None))
        self.labelAcceptanceDecision.setText(_translate("DialogAddNewApplicant", "Accepted?", None))
        self.labelPayment.setText(_translate("DialogAddNewApplicant", "Payment", None))
        self.labelBunkhouse.setText(_translate("DialogAddNewApplicant", "Bunkhouse", None))
        self.checkBoxPayment.setText(_translate("DialogAddNewApplicant", "Check Recieved?", None))
        self.label_5.setText(_translate("DialogAddNewApplicant", "Address:", None))
        self.labelEquipmentsCheck.setText(_translate("DialogAddNewApplicant", "Equipments", None))
        self.labelLine2.setText(_translate("DialogAddNewApplicant", "Line 2", None))
        self.checkBoxFormsCheck.setText(_translate("DialogAddNewApplicant", "Camper has all required forms?", None))
        self.labelLine1.setText(_translate("DialogAddNewApplicant", "Line 1", None))
        self.labelCamp.setText(_translate("DialogAddNewApplicant", "Camp Interested", None))
        self.labelState.setText(_translate("DialogAddNewApplicant", "State", None))
        self.labelCity.setText(_translate("DialogAddNewApplicant", "City", None))
        self.labelEmergencyName.setText(_translate("DialogAddNewApplicant", "Name", None))
        self.labelTribe.setText(_translate("DialogAddNewApplicant", "Tribe", None))
        self.labelFormsCheck.setText(_translate("DialogAddNewApplicant", "Forms", None))
        self.label_14.setText(_translate("DialogAddNewApplicant", "Emergency Contact:", None))
        self.labelCellPhone.setText(_translate("DialogAddNewApplicant", "Cell Phone", None))
        self.label_17.setText(_translate("DialogAddNewApplicant", "Admin:", None))
        self.labelZipCode.setText(_translate("DialogAddNewApplicant", "ZipCode", None))
        self.labelEmail.setText(_translate("DialogAddNewApplicant", "Email:", None))
        self.labelHomePhone.setText(_translate("DialogAddNewApplicant", "Home Phone", None))
        self.checkBoxEquipmentsCheck.setText(_translate("DialogAddNewApplicant", "Camper has all required equipments?", None))
        self.labelEmergencyPhone.setText(_translate("DialogAddNewApplicant", "Phone", None))
        self.pushButtonSubmit.setText(_translate("DialogAddNewApplicant", "Submit", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    DialogAddNewApplicant = QtGui.QDialog()
    ui = Ui_DialogAddNewApplicant()
    ui.setupUi(DialogAddNewApplicant)
    DialogAddNewApplicant.show()
    sys.exit(app.exec_())

