 
codecov:
  notify:
    require_ci_to_pass: yes
  token: 632bd6d7-f5c8-49d1-90fb-09ff22c1630a
  ci:
    - !ci.appveyor.com

coverage:
  precision: 2
  round: up
  range: "20...100"

  status:
    project: yes
    patch: yes
    changes: no

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "header, diff"
  behavior: default
  require_changes: no