from tkinter import *
import sqlite3

class menu:
    def __init__(self, master):
        self.master = master
        frame = Frame(master)
        frame.pack()
        self.title = Label(frame, text="Menu")
        self.title.grid(row=0)
        self.Newapp = Button(frame, text="New applicants", command=self.newApplicant)
        self.Newapp.grid(row=1)
        self.ViewModify = Button(frame, text="View/Modify", command=self.ViewModify)
        self.ViewModify.grid(row=2)
        self.Payment = Button(frame, text="Payment", command=self.payment)
        self.Payment.grid(row=3)

    def newApplicant(self):
        self.master.destroy()
        top = Tk()
        top.title("New Applicant")
        label_1 = Label(top, text="First Name")
        label_2 = Label(top, text="Last Name")
        entry_1 = Entry(top)
        entry_2 = Entry(top)
        label_1.grid(row=0, sticky=W)
        label_2.grid(row=1, sticky=W)
        label_3 = Label(top, text="Age")
        label_4 = Label(top, text="Gender")
        entry_3 = Entry(top)
        entry_4 = Entry(top)
        label_1.grid(row=0, sticky=W)
        label_2.grid(row=1, sticky=W)
        entry_1.grid(row=0, column=1)
        entry_2.grid(row=1, column=1)
        label_3.grid(row=2, sticky=W)
        label_4.grid(row=3, sticky=W)
        entry_3.grid(row=2, column=1)
        entry_4.grid(row=3, column=1)
        button1 = Button(top, text = "Submit",fg="red", command=self.submit)
        button2 = Button(top, text = "Quit",fg="green", command=quit)
        button1.grid(row=4)
        button2.grid(row=4, column=1)
'''
github
'''
    def ViewModify(self):
        self.master.destroy()
        top = Tk()
        top.title("View and Modify")
        label_1 = Label(top, text="First Name")
        label_2 = Label(top, text="Last Name")
        entry_1 = Entry(top)
        entry_2 = Entry(top)
        label_1.grid(row=0, sticky=W)
        label_2.grid(row=1, sticky=W)
        label_3 = Label(top, text="Age")
        label_4 = Label(top, text="Gender")
        entry_3 = Entry(top)
        entry_4 = Entry(top)
        label_1.grid(row=0, sticky=W)
        label_2.grid(row=1, sticky=W)
        entry_1.grid(row=0, column=1)
        entry_2.grid(row=1, column=1)
        label_3.grid(row=2, sticky=W)
        label_4.grid(row=3, sticky=W)
        entry_3.grid(row=2, column=1)
        entry_4.grid(row=3, column=1)
        button1 = Button(top, text = "View/Modify",fg="red")
        button2 = Button(top, text = "Quit",fg="green", command=quit)
        button1.grid(row=4)
        button2.grid(row=4, column=1)

    def payment(self):
        self.master.destroy()
        top = Tk()
        top.title("Payment or refund")
        label_1 = Label(top, text="First Name")
        label_2 = Label(top, text="Last Name")
        entry_1 = Entry(top)
        entry_2 = Entry(top)
        label_1.grid(row=0, sticky=W)
        label_2.grid(row=1, sticky=W)
        entry_1.grid(row=0, column=1)
        entry_2.grid(row=1, column=1)
        button1 = Button(top, text = "View/Modify",fg="red")
        button2 = Button(top, text = "Quit",fg="green", command=quit)
        button1.grid(row=4)
        button2.grid(row=4, column=1)

    def submit(self):
        fname = top.entry_1.get()
        print(fname)

root = Tk()
u = menu(root)
root.mainloop()